; https://docs.platformio.org/page/projectconf.html

[common]
build_flags =
    -I $PROJECT_INCLUDE_DIR
    -Wall
    -Wextra

[env:development]
board           = esp32-s3-devkitc-1
build_flags     =
    ${common.build_flags}
framework       = espidf
lib_deps        =
    throwtheswitch/Unity
monitor_raw     = yes
monitor_speed   = 115200
platform        = espressif32@7.0.1
test_framework  = unity
