; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
build_flags =
    ; USB configuration
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

    ; Essential warnings
    -Wall
    -Wextra

    ; Add /include folder
    -I $PROJECT_INCLUDE_DIR


[env:esp32-s3-devkitm-1]
platform        = espressif32
board           = esp32-s3-devkitm-1
framework       = arduino
monitor_raw     = yes                   ; required for colored debug messages
monitor_speed   = 115200
extends         = common

lib_deps =
    fastled/FastLED