name: KiCAD


on:
  push:
    branches: [ "main" ]
    paths:
      - "hardware/**"
      - ".github/workflows/kicad.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "hardware/**"
      - ".github/workflows/kicad.yml"


env:
  KICAD10_3DMODEL_DIR: "./3dmodels"

jobs:
  verify-project:
    name: Verify KiCAD Project
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ "dolphin", "encoder" ]

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1

      - name: Install KiCad 3D Models
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends kicad-packages3d
          mv /usr/share/kicad/3dmodels ./3dmodels

      - name: Verify Rules
        uses: actions-for-kicad/kicad-actions@a9f126ff27df502685a1f0048f45b48e0dd04838 #v2.5-k10.0.5
        with:
          project_file_name: "hardware/projects/${{ matrix.project }}/${{ matrix.project }}.kicad_pro"
          schematic_file_name: "hardware/projects/${{ matrix.project }}/${{ matrix.project }}.kicad_sch"
          pcb_file_name: "hardware/projects/${{ matrix.project }}/${{ matrix.project }}.kicad_pcb"

          footprint_libraries: "dolphin=hardware/library/footprints"
          symbol_libraries: "dolphin=hardware/library/symbols/dolphin.kicad_sym"

          run_erc: true
          run_drc: true

      - name: DRC Report
        if: always()
        run: |
          if [ -f drc.rpt ]; then
            cat drc.rpt
          fi

      - name: ERC Report
        if: always()
        run: |
          if [ -f erc.rpt ]; then
            cat erc.rpt
          fi

      - name: Export SCH PDF
        uses: actions-for-kicad/kicad-actions@a9f126ff27df502685a1f0048f45b48e0dd04838 #v2.5-k10.0.5
        with:
          project_file_name: "hardware/projects/${{ matrix.project }}/${{ matrix.project }}.kicad_pro"
          schematic_file_name: "hardware/projects/${{ matrix.project }}/${{ matrix.project }}.kicad_sch"

          symbol_libraries: "dolphin=hardware/library/symbols/dolphin.kicad_sym"

          schematic_output_pdf_file_name: "hardware/projects/${{ matrix.project }}/${{ matrix.project }}.pdf"
          schematic_output_pdf: true


      - name: Export PCB STEP
        uses: actions-for-kicad/kicad-actions@a9f126ff27df502685a1f0048f45b48e0dd04838 #v2.5-k10.0.5
        with:
          project_file_name: "hardware/projects/${{ matrix.project }}/${{ matrix.project }}.kicad_pro"
          pcb_file_name: "hardware/projects/${{ matrix.project }}/${{ matrix.project }}.kicad_pcb"

          footprint_libraries: "dolphin=hardware/library/footprints"

          pcb_output_step_file_name: "hardware/projects/${{ matrix.project }}/${{ matrix.project }}.step"
          pcb_output_step: true

      - name: Export PCB Image Top
        uses: actions-for-kicad/kicad-actions@a9f126ff27df502685a1f0048f45b48e0dd04838 #v2.5-k10.0.5
        with:
          project_file_name: "hardware/projects/${{ matrix.project }}/${{ matrix.project }}.kicad_pro"
          pcb_file_name: "hardware/projects/${{ matrix.project }}/${{ matrix.project }}.kicad_pcb"

          footprint_libraries: "dolphin=hardware/library/footprints"

          pcb_output_image_file_name: "hardware/projects/${{ matrix.project }}/images/${{ matrix.project }}_top.png"
          pcb_output_image_side: "top"
          pcb_output_image_background: "transparent"
          pcb_output_image_width: 1920
          pcb_output_image_floor: false
          pcb_output_image_perspective: false
          pcb_output_image_zoom: "1.0"
          pcb_output_image_quality: "high"
          pcb_output_image_rotate: "0,0,0"
          pcb_output_image: true

      - name: Export PCB Image Bottom
        uses: actions-for-kicad/kicad-actions@a9f126ff27df502685a1f0048f45b48e0dd04838 #v2.5-k10.0.5
        with:
          project_file_name: "hardware/projects/${{ matrix.project }}/${{ matrix.project }}.kicad_pro"
          pcb_file_name: "hardware/projects/${{ matrix.project }}/${{ matrix.project }}.kicad_pcb"

          footprint_libraries: "dolphin=hardware/library/footprints"

          pcb_output_image_file_name: "hardware/projects/${{ matrix.project }}/images/${{ matrix.project }}_bottom.png"
          pcb_output_image_side: "bottom"
          pcb_output_image_background: "transparent"
          pcb_output_image_width: 1920
          pcb_output_image_floor: false
          pcb_output_image_perspective: false
          pcb_output_image_zoom: "1.0"
          pcb_output_image_quality: "high"
          pcb_output_image_rotate: "0,0,0"
          pcb_output_image: true

      - name: Upload Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
        with:
          name: artifacts-${{ matrix.project }}
          path: |
            **/hardware/projects/${{ matrix.project }}/${{ matrix.project }}.pdf
            **/hardware/projects/${{ matrix.project }}/${{ matrix.project }}.step
            **/hardware/projects/${{ matrix.project }}/images/*.png


  auto-commit:
    name: Auto Commit Modified Files
    needs:
      - verify-project
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          persist-credentials: true

      - name: Download Artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c #v8.0.1
        with:
          pattern: "artifacts-*"
          merge-multiple: true
          path: .

      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d #v7.2.0
        with:
          commit_message: "chore(ci): update generated KiCAD files [skip ci]"
          file_pattern: 'hardware/**/*.pdf hardware/**/*.png hardware/**/*.step'
