name: PlatformIO

on:
    pull_request:
        branches: [ "main" ]
        paths:
          - 'components/**'
          - 'src/**'
          - 'platformio.ini'
          - 'sdkconfig.defaults'
        types:
          - opened
          - synchronize
    workflow_dispatch:

jobs:
    compilation-firmware:
        name: Verify Firmware Compilation
        permissions:
            contents: read
        runs-on: ubuntu-latest

        steps:
          - name: Checkout
            uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0

          - name: Cache Data
            uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 #v6.1.0
            with:
                path: |
                    ~/.cache/pip
                    ~/.platformio/.cache
                key: ${{ runner.os }}-pio

          - name: Setup Python
            uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 #v6.3.0
            with:
                python-version: '3.11'

          - name: PlatformIO Installation
            run: pip install --upgrade platformio

          - name: Verify Firmware Compilation
            run: pio run -e development
